# This file allows user to override the factory
# defaults with their own settings.

# Enable IMPS or not
gEnableImps=1

# Enable BMPS or not
gEnableBmps=1

# Phy Mode (auto, b, g, n, etc)
gDot11Mode=0

# CSR Roaming Enable(1) Disable(0)
gRoamingTime=0

# 802.11n Protection flag
gEnableApProt=1

# UAPSD service interval for VO,VI, BE, BK traffic
InfraUapsdVoSrvIntv=0
InfraUapsdViSrvIntv=0
InfraUapsdBeSrvIntv=0
InfraUapsdBkSrvIntv=0

# Flag to allow STA send AddTspec even when ACM is Off
gAddTSWhenACMIsOff=1

# Scan Timing Parameters
# gPassiveMaxChannelTime=110
# gPassiveMinChannelTime=60
gActiveMaxChannelTime=40
gActiveMinChannelTime=20

# SOFTAP Channel Range selection
gAPChannelSelectStartChannel=1
gAPChannelSelectEndChannel=11

# 802.11d support
g11dSupportEnabled=0

# CCX Support and fast transition
CcxEnabled=0
FastTransitionEnabled=1
ImplicitQosIsEnabled=0

gNeighborScanTimerPeriod=200
gNeighborLookupThreshold=76
gNeighborReassocThreshold=81

# Legacy (non-ESE, non-802.11r) Fast Roaming Support
# To enable, set FastRoamEnabled=1
# To disable, set FastRoamEnabled=0
FastRoamEnabled=1

# Check if the AP to which we are roaming is better than current AP in
# terms of RSSI.  Checking is disabled if set to 0. Otherwise it will
# use this value as to how better the RSSI of the new/roamable AP should
# be for roaming
RoamRssiDiff=5

# To enable, set gRoamIntraBand=1 (Roaming within band)
# To disable, set gRoamIntraBand=0 (Roaming across band)
gRoamIntraBand=0

# Sets RSSI preference for 5GHz over 2.4GHz AP.
gRoamPrefer5GHz=1

# Give opportunity to last connected BSS in roaming if this much better than candidate
# Set to 0 to disable.
gSelect5GHzMargin=5

# RSSI threshold offset for 2G to 5G roam
roam_bad_rssi_thresh_offset_2g=40

gRoamRescanRssiDiff=5
gRoamBmissFirstBcnt=10
gRoamBmissFinalBcnt=20

# To enable, set gEnableDFSChnlScan=1
# To disable, set gEnableDFSChnlScan=0
gEnableDFSChnlScan=1

# Enable/Disable LPASS support
# 0 to disable, 1 to enable
gEnableLpassSupport=1

# Enable support for TDLS
# 0 - disable
# 1 - enable
gEnableTDLSSupport=1

# Enable support for TDLS offchannel
gEnableTDLSOffChannel=1

# Enable support for TDLS WMM mode
gEnableTDLSWmmMode=1

# Wifi Scanning
# 0: disabled
# 1: enabled
gEnableStrictRegulatoryForFCC=1

# Maximum number of concurrent connections
gMaxConcurrentActiveSessions=3

# Enable or Disable p2p device address administered
isP2pDeviceAddrAdministrated=0

# Enable VHT on 2.4Ghz
gEnableVhtFor24GHzBand=1

# Maximum Receive AMPDU size (VHT only. Valid values: 0->8k 1->16k 2->32k 3->64k 4->128k)
gVhtAmpduLenExponent=7

# Maximum MPDU length (VHT only. Valid values: 0->3895 octets, 1->7991 octets, 2->11454 octets)
gVhtMpduLen=2

# Enable/Disable LPHB
lphbEnableItem=1

# Enable or Disable MCC Adaptive Scheduler at the FW
# 1=Enable (default), 0=Disable
gEnableMCCAdaptiveScheduler=1

# Scan offload
gEnableDirectedScanOffload=1

# Enable FastPath for Rx
gEnableFastPath=1

# WOW Enable/Disable
# 0 - Disable both magic pattern match and pattern byte match.
# 1 - Enable magic pattern match on all interfaces.
# 2 - Enable pattern byte match on all interfaces.
# 3 - Enable both magic patter and pattern byte match on all interfaces.
# Default value of gEnableWoW is 3.
gEnableWoW=3

# Disable/enable SIFS burst
# 0 - disabled (default)
# 1 - enabled
gEnableSifsBurst=1

# Tx Chain Mask for CCK
gCckChainMaskEnable=1

# Tx Chain Mask for 1SS
gTxChainMask1ss=1

# Enable Rx thread separation
# 0 - Disable (default)
# 1 - Enable
rx_thread_affinity_mask=2
