# GPS configuration file

# XTRA
XTRA_SERVER_1=https://xtrapath1.izatcloud.net/xtra3grc.bin
XTRA_SERVER_2=https://xtrapath2.izatcloud.net/xtra3grc.bin
XTRA_SERVER_3=https://xtrapath3.izatcloud.net/xtra3grc.bin

# NTP
NTP_SERVER=time.izatcloud.net

# Capabilities
CAPABILITIES=0x37

# Accuracy
ACCURACY_THRES=5000

# Intermediate position report
INTERMEDIATE_POS=1

# WiFi positioning
ENABLE_WIPER=1

# SUPL
SUPL_HOST=supl.google.com
SUPL_PORT=7275
SUPL_VER=0x20000
SUPL_MODE=1
SUPL_ES=1

# LTE Positioning Protocol
LPP_PROFILE=0

# Sensor
SENSOR_USAGE=1
SENSOR_CONTROL_MODE=0
SENSOR_PROVIDER=1

# Barometer
SENSOR_ALGORITHM_CONFIG_MASK=0x1

# Vehicle network
EXTERNAL_DR_ENABLED=0
